---
# To be run on Node # 1
- name: Initialize Cluster on Node 1
  hosts: "{{ groups['docker_swarm_managers'][0] }}"
  become: true

  tasks:
    - name: Get IP on Node 1
      register: node1_ip
      command: hostname -i

    - name: Store Node 1 IP as fact
      set_fact:
        manager_ip: "{{ node1_ip.stdout }}"

    # - name: Initialize Cluster
    #   command: docker swarm init --advertise-addr {{ node1_ip.stdout }}

    - name: Fetch Manager Token
      register: cluster_manager_token
      command: docker swarm join-token manager -q

    - name: Fetch Worker Token
      register: cluster_worker_token
      command: docker swarm join-token worker -q

    - name: Store Manager Token as fact
      set_fact:
        manager_token: "{{ cluster_manager_token.stdout }}"

    - name: Store Worker Token as fact
      set_fact:
        worker_token: "{{ cluster_worker_token.stdout }}"

    - name: Print Info of Cluster
      debug:
        msg: 
          - "IP of Manager: {{ node1_ip.stdout }}"
          - "Token for Manager: {{ cluster_manager_token.stdout }}"
          - "Token for Worker: {{ cluster_worker_token.stdout }}"

# To be run on Node # 2
- name: Join Cluster as Manager
  hosts: "{{ groups['docker_swarm_managers'][1] }}"
  become: true

  tasks:
    - name: Get Node 1 IP from hostvars
      set_fact:
        manager_ip: "{{ hostvars[groups['docker_swarm_managers'][0]]['manager_ip'] | default('') }}"

    - name: Get Manager Token from hostvars
      set_fact:
        manager_token: "{{ hostvars[groups['docker_swarm_managers'][0]]['manager_token'] | default('') }}"

    - name: Join Cluster
      command: docker swarm join --token {{ manager_token }} {{ manager_ip }}:2377


# To be run on Node # 3,4,5
- name: Join Cluster as Worker
  hosts: docker_swarm_workers
  become: true

  tasks:
    - name: Get Node 1 IP from hostvars
      set_fact:
        manager_ip: "{{ hostvars[groups['docker_swarm_managers'][0]]['manager_ip'] | default('') }}"

    - name: Get Worker Token from hostvars
      set_fact:
        worker_token: "{{ hostvars[groups['docker_swarm_managers'][0]]['worker_token'] | default('') }}"

    - name: Join Cluster
      command: docker swarm join --token {{ worker_token }} {{ manager_ip }}:2377
