version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpassword
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    depends_on:
      - mysql
      - zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpassword
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "UTC"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zabbix-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    restart: always
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Zabbix Agent"
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - zabbix-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

volumes:
  mysql_data:

networks:
  zabbix-net:
    driver: overlay
